"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const objection_1 = require("objection");
const uuid = require("uuid");
class BaseModel extends objection_1.Model {
    async $beforeInsert(context) {
        await super.$beforeInsert(context);
        const ths = this;
        if (ths.autoGeneratedId && ths[ths.autoGeneratedId()]) {
            ths[ths.autoGeneratedId()] = uuid.v4();
        }
    }
}
exports.BaseModel = BaseModel;
//# sourceMappingURL=baseModel.js.map