import {Model, QueryContext} from 'objection';
import * as uuid from 'uuid';

export class BaseModel extends Model {

    async $beforeInsert(context: QueryContext) {
        await super.$beforeInsert(context);
        const ths = this as any;
        if(ths.autoGeneratedId && ths[ths.autoGeneratedId()]) {
            ths[ths.autoGeneratedId()] = uuid.v4();
        }
    }
}